apiVersion: apps/v1
kind: Deployment
metadata:
  name: budgetme-backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: budgetme-backend-pod
  template:
    metadata:
      labels:
        app: budgetme-backend-pod
    spec:
      containers:
        - name: budgetme-backend
          image: huseinnashr/budgetme-backend:#{RELEASE_VERSION}
          imagePullPolicy: Always