name: "Release to Production"

on:
  push:
    tags: 
    - '*-production'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set REALEASE_VERSION
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: sed -i "s/#{RELEASE_VERSION}/$RELEASE_VERSION/g" ./files/config/production.yaml && head ./files/config/production.yaml
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t huseinnashr/budgetme-backend:$RELEASE_VERSION .
      - run: docker push huseinnashr/budgetme-backend:$RELEASE_VERSION
      - run: sed -i "s/#{RELEASE_VERSION}/$RELEASE_VERSION/g" ./k8s/prod/budgetme-backend-depl.yaml && head ./k8s/prod/budgetme-backend-depl.yaml
